layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

# permalink: /:year/:month/:day/:title/
permalink: /:title/

defaults:
  -
    scope:
      path: "/blog" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by:
    #     - pushed
    # - stars
  limit: 12
  exclude:
    archived: false
    forks: false
    projects:
      - travisci-test
      - community-starter-kit
      - continuous-integration-travis
      - getting-started-github-apps
      - github-slideshow
      - HTMLPortfolioProject
      - HelloCodeSchoolProject
      - slackin-auto

social_media:
  # behance: your_username
  dribbble: josecage
  facebook: prince.josecage
  hackerrank: josecage
  instagram: jose.cage
  # keybase: your_username
  linkedin: josecage
  medium: JoseCage
  # stackoverflow: your_user_id
  telegram: josecage
  twitter: cagejose
  # unsplash: josecage
  buymeacoffee: januario
  makerlog: josecage
  # vk: your_username
  # website: https//your_website_url
  # youtube: your_username

topics:
  - name: Laravel
    web_url: https://github.com/topics/laravel
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/laravel/laravel.png

  - name: Bash
    web_url: https://github.com/topics/bash
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/bash/bash.png

    #  - name: Elixir
    #    web_url: https://github.com/topics/elixir
    #    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/elixir/elixir.png

  - name: Android
    web_url: https://github.com/topics/android
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/android/android.png
